name: Autograding Tests
on:
  - push
  - repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'oracle'
          java-version: '23'

      - name: Download JavaFX
        run: |
          wget https://download2.gluonhq.com/openjfx/23.0.2/openjfx-23.0.2_linux-x64_bin-sdk.zip -O openjfx.zip
          unzip -q openjfx.zip -d ${{ github.workspace }}
          mv ${{ github.workspace }}/javafx-sdk-23.0.2 ${{ github.workspace }}/javafx-sdk

      - name: CheckStyle
        id: checkstyle
        uses: classroom-resources/autograding-command-grader@v1
        with:
          test-name: CheckStyle
          setup-command: |
            wget --no-verbose https://github.com/checkstyle/checkstyle/releases/download/checkstyle-10.21.1/checkstyle-10.21.1-all.jar;
            wget --no-verbose https://csse.msoe.us/csc1110/MSOE_checkStyle.xml;
          command: java -jar checkstyle-10.21.1-all.jar -c MSOE_checkStyle.xml -e src/test/*.java
            src/**/*.java;
          timeout: 10

      - name: Unit Tests
        id: unit-tests
        uses: classroom-resources/autograding-command-grader@v1
        with:
          test-name: Unit Tests
          setup-command: |
            wget --no-verbose https://repo1.maven.org/maven2/org/junit/platform/junit-platform-console-standalone/1.11.4/junit-platform-console-standalone-1.11.4.jar;
            javac -d target -cp .:junit-platform-console-standalone-1.11.4.jar:${{ github.workspace }}/lib/ImageUtil.jar:${{ github.workspace }}/javafx-sdk/lib/* \
            --module-path ${{ github.workspace }}/javafx-sdk/lib/ \
            --add-modules javafx.controls,javafx.fxml,javafx.swing \
            src/**/*.java          
          command: |
            java -cp target:junit-platform-console-standalone-1.11.4.jar:${{ github.workspace }}/lib/ImageUtil.jar:${{ github.workspace }}/javafx-sdk/lib/* --module-path ${{ github.workspace }}/javafx-sdk/lib/ --add-modules javafx.controls,javafx.fxml,javafx.swing -Djavafx.platform=gtk -Dprism.order=sw -jar junit-platform-console-standalone-1.11.4.jar --class-path target --select-class test.TestSuite
          timeout: 10

      - name: Autograding Reporter
        uses: classroom-resources/autograding-grading-reporter@v1
        env:
          CHECKSTYLE_RESULTS: "${{steps.checkstyle.outputs.result}}"
          UNIT-TESTS_RESULTS: "${{steps.unit-tests.outputs.result}}"
        with:
          runners: checkstyle,unit-tests