name: Autograding Tests
'on':
  - push
  - repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'oracle'
          java-version: '23'
      - name: Download JavaFX
        run: |
          wget https://download2.gluonhq.com/openjfx/23.0.1/openjfx-23.0.1_linux-x64_bin-sdk.zip
          unzip -q openjfx-23.0.1_linux-x64_bin-sdk.zip -d ${{ github.workspace }}
          mv ${{ github.workspace }}/javafx-sdk-23.0.1 ${{ github.workspace }}/javafx-sdk

      - name: Download JUnit Platform Console
        run: |
          mkdir -p lib
          wget -q https://repo1.maven.org/maven2/org/junit/platform/junit-platform-console-standalone/1.11.4/junit-platform-console-standalone-1.11.4.jar -O lib/junit-platform-console-standalone.jar

      - name: CheckStyle
        id: checkstyle
        uses: classroom-resources/autograding-command-grader@v1
        with:
          test-name: CheckStyle
          setup-command: |
            wget --no-verbose https://github.com/checkstyle/checkstyle/releases/download/checkstyle-10.21.1/checkstyle-10.21.1-all.jar;
            wget --no-verbose https://csse.msoe.us/csc1110/MSOE_checkStyle.xml;
          command: java -jar checkstyle-10.21.1-all.jar -c MSOE_checkStyle.xml -e src/test/*.java
            src/**/*.java;
          timeout: 10

      - name: Compile Java code
        run: |
          mkdir -p bin
          javac -cp "lib/*:${{ github.workspace }}/javafx-sdk/lib/*" \
                --module-path ${{ github.workspace }}/javafx-sdk/lib/ \
                --add-modules javafx.controls,javafx.fxml \
                -d bin src/**/*.java

      # Run Unit Tests
      - name: Unit Tests
        id: tests
        run: |
          java -cp "bin:lib/*:${{ github.workspace }}/javafx-sdk/lib/*" \
               --module-path ${{ github.workspace }}/javafx-sdk/lib/ \
               --add-modules javafx.controls,javafx.fxml \
               --add-opens javafx.graphics/com.sun.javafx.util=ALL-UNNAMED \
               --add-opens javafx.graphics/com.sun.glass.ui=ALL-UNNAMED \
               --add-opens javafx.graphics/com.sun.javafx.application=ALL-UNNAMED \
               --add-opens javafx.base/com.sun.javafx.logging=ALL-UNNAMED \
               --add-exports javafx.graphics/com.sun.javafx.tk=ALL-UNNAMED \
               --add-exports javafx.graphics/com.sun.javafx.scene=ALL-UNNAMED \
               --add-exports javafx.graphics/com.sun.javafx.scene.layout=ALL-UNNAMED \
               --add-exports javafx.base/com.sun.javafx.event=ALL-UNNAMED \
               --add-exports javafx.base/com.sun.javafx.logging=ALL-UNNAMED \
               -Dtestfx.headless=true \
               -Dmonocle.platform=Headless \
               -Dprism.order=sw \
               org.junit.platform.console.ConsoleLauncher \
               --scan-class-path \
               --class-path bin
        timeout-minutes: 5